"""stock_audits: admin stock change audit

Revision ID: 4d777d0c147c
Revises: bc6a7c07f4ef
Create Date: 2026-07-18 21:56:48.598584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d777d0c147c'
down_revision: Union[str, Sequence[str], None] = 'bc6a7c07f4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_audits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('machine_item_id', sa.BigInteger(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('stock_before', sa.Integer(), nullable=False),
    sa.Column('stock_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_item_id'], ['machine_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_audits_machine_item_id'), 'stock_audits', ['machine_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_audits_machine_item_id'), table_name='stock_audits')
    op.drop_table('stock_audits')
    # ### end Alembic commands ###
